apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: techtrends
  strategy: {}
  template:
    metadata:     
      labels:
        app: techtrends
    spec:
      containers:
      - image: {{ .Values.image.repository }} : {{ .Values.image.tag }}
        name: techtrends
        ports:
        - containerPort: {{ .Values.containerPort }}      
          protocol: {{ .Values.service.protocol }}
        livenessProbe:
          initialDelaySeconds: 10  
          periodSeconds: 5
          httpGet:
            path: {{ .Values.livenessProbe.path }}
            port: 3111
        readinessProbe:
          initialDelaySeconds: 10 
          periodSeconds: 5
          httpGet:
            path: {{ .Values.readinessProbe.path }}        
            port: 3111
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
